# Generated by Django 6.0.2 on 2026-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_photos/", verbose_name="Изображение"),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("count_views", models.IntegerField(default=0, verbose_name="Просмотры")),
                ("created_at", models.DateField(auto_now_add=True, db_index=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="Дата изменения")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-created_at"],
            },
        ),
    ]
