# Generated by Django 6.0.2 on 2026-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, help_text="Отметьте для публикации", verbose_name="Опубликовано"),
        ),
    ]
